SELECT
COLUMN_NAME AS "colunm Name",
COLUMN_TYPE AS "Data Type"
IS_NULLABLE AS "Is Nullable",
COLUMN_KEY AS "Key",
EXTRA AS "Extra Info"
FROM
information_schema.COLUMN
WHERE
TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = "Books"
ORDER BY
ORDINAL_POSITION;
